"""add_status_to_documents

Revision ID: d542ced8aeea
Revises: 37e43d5502df
Create Date: 2026-01-28 19:01:05.744937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d542ced8aeea"
down_revision: Union[str, None] = "37e43d5502df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("status", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "status")
    # ### end Alembic commands ###
